# Discussion VIII (Prop 11-13)

## Review Proposition 11
>To draw a straight line at right angles to a given straight line from a given point on it.

In our last discussion, we went through Proposition 11 very quickly. Now we slow down to review it and take time to focus on the format of writing:

 - **Proposition number:** Proposition XI<br>
 - **The abstract and general proposition heading:**<br>
To draw a straight line at right angles to a given straight line from a given point on it.<br>
Translate the propositional content into concrete images and letter symbols, i.e., translate the proposition into what the proof will present next.<br>
Let AB be the given straight line, and C the given point on it.<br>
Thus it is required to draw from the point C a straight line at right angles to the straight line AB.<br>
 - **Graphing and making conclusions on specific images and symbols.** <br>
	Let a point D be taken at random on AC;<br>
let CE be made equal to CD; [I. 3]<br>
on DE let the equilateral triangle FDE be constructed, and let FC be joined; [I. 1]<br>
I say that the straight line FC has been drawn at right angles to the given straight line AB from C the given point on it.<br>
 - **Details of the proof:** <br>
For, since DC is equal to CE, and CF is common, the two sides DC, CF are equal to the two sides EC, CF respectively; and the base DF is equal to the base FE;<br>
therefore the angle DCF is equal to the angle ECF; [I. 8] and they are adjacent angles.<br>
But, when a straight line set up on a straight line makes the adjacent angles equal to one another, each of the equal angles is right; [Def. 10] therefore each of the angles DCF, FCE is right.<br>
 - **Statement of completion proof:** <br>
Therefore the straight line CF has been drawn at right angles to the given straight line AB from the given point C on it. <br>
Q.E.F.<br>

You will notice that Euclid did not draw the diagram while writing the proof, but first drew the diagram and then proved it, separately. What does this mean? It means that the proofs in the book Elements are not a simple demonstration of the proof process, but a summary and reorganization after the proof. It is like we need a draft to write a proof and a final version on the exam paper, the proof in Elements that we see is just a final version. So sometimes we say that Euclid is very thoughtful and his reasoning is flowing. But it may not be done from the very beginning, instead, it may be gradually added and perfected. The developed format that he displays his proof is worthy learning.

First of all, each proposition has a serial number that simply represents it, followed by a concise summary. After the proof begins, the abstract content, which is not easy to understand, is first visualized by the image, text, symbols. Then the steps for constructing the diagram are described, followed by a return to the original point on the complete image to begin the proof. After the proof is complete there is a statement to mark its completion. You see that it is formatted with a beginning and an end, very clearly. This approach is particularly suitable for writing to communicate with people, even if it is not a proof but a lab report, you can present your work in this format, and if it is a report, it would look like the following:

 - Title, date (author)
 - Overview of the report (further explanation of the title, including concepts, methodology, etc.)
 - Putting conceptual issues into practice, describing the relevant experimental equipment, background, and linking the experiment to the topic of the report
 - Important experimental steps and results
 - Specific experimental procedures
 - Final return of the experiment to the topic of the report

This format takes full account of the reader's receptiveness, from the topic, to the overview, to the figurative problem, to the steps and summary of the solution. This strategy of format construction can be applied on different report-based document writing, which does not necessarily present a thought process, yet is reader-friendly, very systematic, and highly readable. In contrast to this is the prose type of writing, or the exploration from a problem, often it presents the author's thought process, but it is also easy to take the reader off the road and miss the important discoveries. When writing, it is important to choose the appropriate approach with reference to the object and purpose of the writing. Disciplines such as math or science are written with a generalized purpose, hence a clear format and structure is particularly important. In the case of literature, the focus is more on the description of individual experiences, empathizing with the reader in detail, and the reader receives not the same environment but the emotions, thoughts, and the conveyed individual reactions.

## Proposition 12
>To a given infinite straight line, from a given point which is not on it, to draw a perpendicular straight line.

After the extensive discussion of format, we move forward to Proposition 12 and 13. Proposition 12 is closely related to proposition 11 and looks somewhat similar, thus also making us wonder why these two cannot be combined in the same proposition. At first, you may wonder about the progression of right angles and perpendicular lines, but then I realized that it is better to look at it in another way: if you read carefully the expressions of the two proofs, you will see that there is still a slight difference in the conditions. Proposition 11, it’s still a point on the line, and Proposition 12, it extends the scope to a point outside the line. In other words, Proposition 11 is still within the study of the "three lines one theorem", which requires the application of equilateral triangles, while the perpendicular line in Proposition 12 walks out the top/bottom angle of the triangle. It can be any point outside the line in relation to the line.

## Proposition 13
>If a straight line set up on a straight line make angles, it will make either two right angles or angles equal to two right angles.

For Proposition 13, Alex encounters a big confusion: whether a line intersects another line at an angle or not, it should be 180 degrees itself, this is equal to two right angles, thus why we still need this proposition.

To understand this proposition, Alex’s confusion needs to be broken down into two parts.

The first part is whether we describe the straight line in terms of two right angles or 180 degrees. In fact, the aim of our expression is that the sum of the angles made by one line and the other line is constant. It seems that this truth is self-evident from the image. It is correct to say so, and in this proposition we need a metric to describe this fixed quantity. This proposition is not just about proving that there is an equivalent quantity here, but also about expressing that equivalent quantity in the proper way, which is what the second part needs to explain: why it is expressed in terms of two right angles and not 180 degrees.

One of the major obstacles to Alex's learning from the beginning of this course was the obsession with numbers. What is the difference between the concepts of  ‘two right angles’ and ‘180 degrees’? In Alex's eyes, ‘two right angles’ and ‘180 degrees’ both refer to the same image, and in that sense, they do, being the sum of the angels mentioned in the first part, which are equal. However, the difference between these two concepts lies in the fact that their units of measurement are not the same. 

‘Two right angles’ is a right angle * 2, while ‘180 degrees’ is 1 degree * 180. we have the concept of right angle in the definition, but without a protractor, there is no 1 degree and no 180 degrees. That is to say, ‘180 degrees’ misses a cognitive base for application, i.e., a standard unit of measure. For example, I can say that the same image is a flat angle, but we do not define a flat angle, so there is a possibility of misunderstanding, and to avoid ambiguity, we do not use undefined units and terms. Then, if our current units are only right angles and no degrees exist, we need to compare all new ‘angles’ with a right angle.

For these two reasons, propositions have to be declared explicitly.

Another point to note is the strategy of this proposition, which is to draw a right angle with an auxiliary line. Since the unit of measure is a right angle, and the final expression of the quantity is two right angles, it is natural that the auxiliary line needs to create a right angle as a medium for comparison and measurement.We can use the same tech, to identify the purpose and aim of proposition and then find the auxiliary line.

**Open assignment:**

 - Find an article/essay/report that you have written in the past and do a self-analysis on your writing format. Is there anything improvable?
