# Discussion XV  (Prop 33-36)

The propositions in this lesson are about parallelograms. We have divided the propositions to be examined today into two groups: Propositions 33 and 34, a group on the definition and properties of parallelograms; and Propositions 35 and 36, a group on the transfer of the concept of equal areas.

## Proposition 33
>The straight lines joining equal and parallel straight lines [at the extremities which are] in the same directions [respectively] are themselves also equal and parallel.

## Proposition 34
>In parallelogrammic areas the opposite sides and angles are equal to one another, and the diameter bisects the areas.

After exploring the triangle and parallel lines, it’s the turn to parallelogram, however, it is interesting that if we look back at the order of the definition, parallelogram actually existed in the definition of 22, but it appeared before the parallel straight line, and did not appear under the name parallelogram, and the concept of parallelism is not used in the definition -- a rhomboid that which has its opposite sides and angles equal to one another but is neither equilateral nor right- angled? (Excerpt definition XXII), here we may stop a little bit, just to think about: for a  quadrilateral with equal opposite angles and sides, the two sets of sides are necessarily parallel or not? So why didn't we prove parallelism through parallelograms before? Instead, we went through the relations of alternate interior angles, corresponding angles, and interior angles on the same side? Recall here Proposition XXIII: On a given straight line and at a point on it to construct a rectilineal angle equal to a given rectilineal angle. In this proof Euclid is putting the angle inside a triangle and proving that the two linear angles are equal by proving that the triangles are congruent.

Probably there is one difference between triangles and parallelograms. A parallelogram is a set of two parallel lines, and a set of parallel lines can exist independently; a parallelogram emerges when two sets of parallel lines cross under certain circumstances. While two sets of parallel lines depend on each other to produce a new figure, the concept of parallelism is independent from the quadrilateral. A triangle is a figure that can be considered as a straight line folded twice, with its associated extensions, exterior angles, etc., all dependent on the triangle, which itself can no longer be disassembled. Because a triangle can be used as a basic unit, but a parallelogram cannot.

Thus, in the study of propositions, we first understand the concept of parallelism, then build another set of parallel lines on a set of parallel lines to construct a parallelogram, and then prove that its properties satisfy the part of the definition that "opposite sides and angles equal to one another but is neither equilateral nor right- angled". It is only after this that the two concepts overlap and the role from known to proved is completed. Proposition 33 builds a parallelogram on the basis of parallelism, while Proposition 34 proves that the opposite sides of a parallelogram are equal to each other. Interestingly, Proposition33 does not mention "parallelogram" in the text, but only says another set of parallel and equal sides, while Proposition 34 starts with the region of parallelogram immediately after.

In Proposition 34, "area" appears and is not defined, but evolves into area later, so let's describe it by "area", that is, the place where the circle is defined. We have talked before about the bisector of an angle and the bisector of a line, but for the first time we are talking about the bisector of a figure. In Proposition 9, we used two congruent triangles to confirm that the plane angles are bisected, that is, we first confirmed the equality of the two figures and then took out the angular parts of them. And here, for the first time, we talk directly about the graphs (“area”).

Here it can trigger countless imaginations and thoughts about what this graph looks like. Is it an illusion or a solid, is it a closed content enclosed by lines like a fence? Or is it an inseparable existence closely linked to the lines? Can it be separated from the figure itself? In life it seems that examples of both can be found, such as a yard, then the lines are the fence, and the calculation of the area within the yard is separate from the wall itself, because one wants to know the area of land in the yard and how many plants and flowers can be planted. And if we buy a birthday cake, it is another thing. The edge of the cake and the cake itself is a whole, the figure and the edge are continuous together, we abstract the yard and the cake separately, both are geometric figures, while the relationship between the edge and the inner area is very different, what kind of thinking can this bring us?

# Proposition 35
>Parallelograms which are on the same base and in the same parallels are equal to one another.

# Proposition 36
>Parallelograms which are on equal bases and in the same parallels are equal to one another.

Next, we try to prove Proposition 35 and 36, which its methods are not difficult. Proposition 35 is proved by subtracting equal quantities and adding equal quantities to equal quantities, while Proposition 36 builds on the previous proposition and only needs to find a suitable medium as an intermediate bridge.

It is interesting to see the expansion of the concept of equality. The act of comparison - equivalence - was never defined; it seems to be taken directly from the real-life concept and used. Most of the things we proved before were equal because they overlapped, that is, it was hoped that the parts proved to be equal could be used as a continuous whole, with each uncuttable part corresponding to the other. Because overlapping objects are separable, then after motion, the two objects that first overlap and then do not overlap are equal. Here the separation motion has an assumed premise that its separation must be without any loss. For example, translation, flip, and symmetry of these movements, we assume that in the abstract geometric world, will not produce any loss of energy, which will have the equivalence after the separation of the movement. (For a displaced object, there is also such a premise of motion, we assumed that the object has no loss in displacement, otherwise it would not be the same before the motion and it would be the same after the motion)

The first step of equivalence is from coincidence to partial separation, which is the same base in Proposition 35, and then comes the complete separation, which has become equal in Proposition 36 At the same time, in both propositions, it is implied that the case of detachment from the shackles of shape, the same base but the angles are not different, and the parallelogram with the same base between the same set of parallel lines, which does not have the same shape, and their equivalence is also proved in Proposition 35, is done by splicing, which means that we can combine two parallelograms by cutting them and the parts they are divided into, are identical in shape, thus introducing the equivalence of the whole. This is an example of changing perspective and going back to the local and microscopic parts for proof. If we endorse such a leap of logic, then geometry will break through the limits of our vision and take us on to situations approaching infinity. Imagine a parallelogram close to a straight line with a fixed base and a side close to infinity in length. Although it is not known exactly how long it is, its area is known because it can be known from other parallelograms between the same base and the same set of parallelograms, a jump from infinity to finite that is well worth thinking about.
