# Discussion XVI  (Prop 37-42)

Propositions 37 and 38 are a reworking of Propositions 35 and 36. Immediately after, we flip the conditions to reverse the parallel lines graphically in Proposition 39 and Proposition 40. 40 is an expansion, while 42 is a recreation based on this series. These propositions are short, and the proof process is relatively simple based on mastery of Propositions 35 and 36.

## Proposition 37
>Triangles which are on the same base and in the same parallels are equal to one another.

Proposition 37 is a continuation of Proposition 36. On the basis of proving that parallelograms are equal, it is enough to prove that half of the equal quantities are also equal. In Proposition 23 we mentioned a different way of proving the idea, and here it is the use of the filling and comparing method by pushing the larger to the smaller. Previously, we went backwards to the triangle level in order to compare the size of the angles, and now we are pushing it even further to the parallelogram comparison in order to prove the size of the triangle. What is interesting, however, is that if we look at the first volume with a macroscopic view, it basically follows the sequence from angles to figures, and then each jump can again be reverted back a small step to further illustrate the previous partial properties. In fact, this also gives us a life and learning inspiration, some results are a part of the fine processing to get, while some results of the discovery need to cross the perspective to look. For the same piece of knowledge, it does not require a full comprehension, to learn deeper and further and then come back will help the understanding. 

Another controversial point in Proposition 37 is the last step, whether we can use the argument "half of equal quantities are equal" without reasoning. In the common notions, the operation of equal quantities does not involve multiplication and division, but only the addition and subtraction of equal quantities are equal. We can rewrite the argument to say that equal quantities are equal after subtracting half of them, which is the application of Common Notion 3. This is the part of the parallelogram mentioned in Proposition 34 where the diagonal bisects the parallelogram. Note that the rewriting of Common Notion 3 is controversial here, but it is reasonable here because the parallelogram is proved in Proposition 34.

## Proposition 38
>Triangles which are on equal bases and in the same parallels are equal to one another.

The order of Propositions 37 and 38 is an exact copy of Proposition 35 and Proposition 36. The same as Proposition 37, Proposition 38 only ends the proof by adding the last sentence that half of the equal quantities are also equal on the basis of proving that parallelograms are equal under the same conditions, thus the same method and arguments will not be repeated here.

## Proposition 39
>Equal triangles which are on the same base and on the same side are also in the same parallels.

The previous proposition was to prove the connection between triangles by the relation between parallel lines and base sides, but now, proposition 39, it is to restrict the triangle to see parallel lines. Let's think about what parallel lines mean. First, if we just have two triangles with the same side and the same base, the common base is part of one of the parallel lines, and then the other parallel line is not shown at the beginning (note that it cannot be said that it does not exist here, because it is always there, it is just a matter of whether we find it and mark it), it is necessary to connect the vertices of the two triangles in order to draw part of this parallel line. Then the parallel line drawn actually defines to some extent the domain of the triangle, that is, the upper and lower boundaries, and this found boundary has a parallel relationship between them. What can this teach us? Suppose we are looking at a thing, then we also have to think about the nature of the larger range of things that are not accidentally related. From the previous proposition, we know that the property of connecting the vertices of two triangles to appear here is not a coincidence, and this necessity is the direction and content of the new proposition that deserves to be made explicit.

## Proposition 40
>Equal triangles which are on equal bases and on the same side are also in the
same parallels.

The origin of Proposition 40 is doubtful, and it is recorded as a late addition by the editor. However, it follows Proposition 39, and its parallel transformation from "same base" to "equal base" is consistent with the style of Euclid's previous proofs. I personally think that even if it is added by the editor, there is nothing wrong with keeping it.

## Proposition 41
>If a parallelogram have the same base with a triangle and be in the same parallels, the parallelogram is double of the triangle.

After proving parallelograms and triangles in the case of equal bases and between the same set of parallel lines separately, (with the additional content of proving parallel lines in an opposite way), finally we see the proof that integrates parallelograms and triangles together. Proposition 41 qualifies the condition of congruent bases and parallel lines, and carries out a corollary of Propositions 35 and 37. It is worth noting here the concept of doubling, not forgetting our historical question about the discussion of "area" in Proposition 34, whether the area of the figure can be compared here, and what is the baseline for comparison? Although the issue of area units is never mentioned in the book, are they assumed to exist when we make comparisons? This point has never been taken seriously, and the issue of units will be explored further in the definitions in Volume 5.。

## Proposition 42
>To construct, in a given rectilineal angle, a parallelogram equal to given triangle.

The entire book begins with the construction of an equilateral triangle on a straight line. It also makes us wonder if the point of mathematics is to discover or to create, or to reuse? This also has been a question that I leave Alex to think about. Later we also construct triangles here (Proposition 22), straight line angles (Proposition 34), draw parallel lines, etc. Here the parallelogram is constructed, but two qualifications are given, one to limit the size of the angle, the other is to limit the size of the area. Because the previous proposition has proved that, on the same base line and within the same set of parallel lines, the area of parallelograms is twice as the triangles, then it is natural that the area of a parallelogram with half the base is equal to that of a triangle within the same set of parallelograms, so it is only necessary to make the angles equal in size to the given angles when drawing the parallelogram. From Proposition 35 to this proposition, it is all about the back and forth transformation of quadrilaterals and triangles between the same set of parallelograms, and the repeated application of a group of translational transformation techniques, from overlap to partial separation to complete separation, to comparison between the whole and the parts, and stopping at reinvention, that is, at creation. The purpose of mathematics is not only to help us perceive the laws of nature, but from the beginning it has the meaning of recreation.
